workflows:
  ios-build:
    name: OpenIM iOS Build

    instance_type: mac_mini_m2

    environment:
      xcode: latest

    scripts:
      - name: Install CocoaPods
        script: |
          pod repo update

      - name: Install dependencies
        script: |
          pod install

      - name: Show projects and schemes
        script: |
          find . -name "*.xcworkspace"
          find . -name "*.xcodeproj"
          xcodebuild -list

      - name: Build for simulator
        script: |
          xcodebuild \
            -project OpenIMSDKUIKit.xcodeproj \
            -scheme OpenIMSDKUIKit \
            -configuration Release \
            -sdk iphonesimulator \
            CODE_SIGNING_ALLOWED=NO \
            build

    artifacts:
      - "**/*.app"
      - "**/*.xcarchive"
