workflows:
  openim-build:
    name: OpenIM Unsigned IPA

    instance_type: mac_mini_m2

    environment:
      xcode: 16.4

    scripts:
      - name: Install Pods
        script: |
          cd Example
          pod install

      - name: Build OpenIM Example
        script: |
          cd Example

          xcodebuild \
            -workspace OpenIMSDKUIKit.xcworkspace \
            -scheme OpenIMSDKUIKit_Example \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            build

      - name: Find built app
        script: |
          find ~/Library/Developer/Xcode/DerivedData -name "*.app"
          
      - name: Create IPA
        script: |
          APP=$(find ~/Library/Developer/Xcode/DerivedData -name "N-DEMO.app" | head -n 1)
      
          mkdir Payload
          cp -R "$APP" Payload/
      
          zip -qry N-DEMO.ipa Payload

    artifacts:
      - N-DEMO.ipa
